version: '1.0'

services:
  mysql:
    container_name: lifelineBD
    image: vicg0/lifeline-1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pLIJYGRD123!
    ports:
      - "3306:3306"